version: '3.7'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    deploy:
      resources:
        limits:
          memory: 2g
    environment:
      - node.name=es01
      - discovery.type=single-node
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data/01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
    - "5601:5601"
  grafana:
    image: grafana/grafana
    volumes:
    - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/graphite.yml
    ports:
      - "8091:3000"
  graphite:
    image: graphiteapp/graphite-statsd:1.1.6-1
    ports:
    - "8090:80"
    expose:
      - 8080
      - 2003
      - 2004
      - 2023
      - 2024
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  zipkin:
    image: openzipkin/zipkin-slim:2.20.2
    ports:
    - "9411:9411"
#    expose:
#      - 9411
  consul:
    image: consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul-conf/consul.json:/consul/config/consul.json
  ci-core:
    hostname: ci-core
    build: ci-core
    depends_on:
      - consul
      - graphite
      - grafana
      - zipkin
    environment:
      CLOUD_NAME: "pl-poz-01"
    volumes:
      - ./ci-core/src/main/resources/bootstrap.yml:/usr/app/bootstrap.yml
      - ./ci-core/src/main/resources/application.yml:/usr/app/application.yml
    ports:
    - "8001:8001"
    - "5005:5005"
    command: ["java",
              "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005",
              "-jar",
              "/usr/app/ci-core.jar",
              "--spring.profiles.active=metrics",
              "--spring.config.location=/usr/app/bootstrap.yml,/usr/app/application.yml"]
  deploy-runner:
    hostname: deploy-runner
    build: deploy-runner
    depends_on:
      - consul
      - graphite
      - grafana
      - zipkin
    environment:
      CLOUD_NAME: "pl-poz-01"
    volumes:
      - ./deploy-runner/src/main/resources/bootstrap.yml:/usr/app/bootstrap.yml
      - ./deploy-runner/src/main/resources/application.yml:/usr/app/application.yml
    ports:
      - "8002:8002"
      - "5006:5006"
    command: ["java",
              "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006",
              "-jar",
              "/usr/app/deploy-runner.jar",
              "--spring.profiles.active=metrics",
              "--spring.config.location=/usr/app/bootstrap.yml,/usr/app/application.yml"]
